# Site settings
author: Cesar Mendoza
title: Trending Movies
header-img: img/home-bg.png
email: mendoza.cesar92@gmail.com
copyright_name: Cesar Mendoza
description: > # this means to ignore newlines until "baseurl:"
  OO Ruby portfolio project
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mendozacm

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
